import 'dotenv/config';
import express,{NextFunction,Request,Response} from 'express'; import cors from 'cors'; import helmet from 'helmet'; import rateLimit from 'express-rate-limit'; import cookieParser from 'cookie-parser'; import jwt from 'jsonwebtoken'; import bcrypt from 'bcryptjs'; import crypto from 'crypto'; import {PrismaClient,Role,AppointmentStatus,OrganizationStatus,VipExceptionType,VipFrequency} from '@prisma/client'; import {z} from 'zod';
const db=new PrismaClient(); const app=express(); const PORT=Number(process.env.PORT||3000); const JWT_SECRET=process.env.JWT_SECRET||'';
if(!JWT_SECRET || JWT_SECRET.length<32) console.warn('JWT_SECRET must be set to a strong value outside local development.');
app.use(helmet()); app.use(cors({origin:process.env.CORS_ORIGIN?.split(',')||'http://localhost:5173',credentials:true})); app.use(express.json({limit:'64kb'})); app.use(cookieParser()); app.use(rateLimit({windowMs:15*60_000,max:300,standardHeaders:true,legacyHeaders:false}));
type Auth={id:string;role:Role;organizationId:string|null}; declare global {namespace Express {interface Request {auth?:Auth}}}
const fail=(res:Response,status:number,code:string,message:string)=>res.status(status).json({success:false,error:{code,message}});
const asyncRoute=(fn:(r:Request,s:Response,n:NextFunction)=>Promise<unknown>)=>(r:Request,s:Response,n:NextFunction)=>void fn(r,s,n).catch(n);
function tokenFor(user:{id:string;role:Role;organizationId:string|null}){return jwt.sign({sub:user.id,role:user.role,organizationId:user.organizationId},JWT_SECRET,{expiresIn:'8h'});}
function auth(req:Request,res:Response,next:NextFunction){const token=req.cookies.access_token||req.headers.authorization?.replace(/^Bearer /,''); if(!token)return fail(res,401,'UNAUTHENTICATED','Inicia sesión para continuar.'); try {const p=jwt.verify(token,JWT_SECRET) as jwt.JwtPayload; req.auth={id:p.sub!,role:p.role,organizationId:p.organizationId||null}; next();}catch{return fail(res,401,'INVALID_TOKEN','La sesión no es válida o expiró.')}}
function role(...roles:Role[]){return (req:Request,res:Response,next:NextFunction)=>!req.auth||!roles.includes(req.auth.role)?fail(res,403,'FORBIDDEN','No tienes permisos para esta acción.'):next();}
async function activeTenant(req:Request,res:Response,next:NextFunction){if(!req.auth?.organizationId)return fail(res,403,'TENANT_REQUIRED','Esta acción requiere una barbería.'); const o=await db.organization.findUnique({where:{id:req.auth.organizationId}}); if(!o||o.status!==OrganizationStatus.ACTIVE||o.subscriptionExpiresAt<=new Date())return fail(res,403,'ORGANIZATION_SUSPENDED','Esta barbería no está disponible temporalmente.'); next();}
function webhookAuth(req:Request,res:Response,next:NextFunction){return req.header('X-Webhook-Secret')===process.env.N8N_WEBHOOK_SECRET?next():fail(res,401,'INVALID_WEBHOOK_SECRET','Webhook no autorizado.');}
function cronAuth(req:Request,res:Response,next:NextFunction){return req.header('X-Cron-Secret')===process.env.CRON_SECRET?next():fail(res,401,'INVALID_CRON_SECRET','Cron no autorizado.');}
async function sendN8n(event:string,payload:unknown){if(!process.env.N8N_WEBHOOK_URL)return; try{await fetch(process.env.N8N_WEBHOOK_URL,{method:'POST',headers:{'content-type':'application/json','X-Webhook-Secret':process.env.N8N_WEBHOOK_SECRET||''},body:JSON.stringify({event,...(payload as object)})})}catch{console.error('n8n dispatch failed',event)}}
const timeOnDate=(d:Date,time:string)=>{const [h,m]=time.split(':').map(Number);const x=new Date(d);x.setHours(h,m,0,0);return x};
const publicOrg=async(slug:string)=>db.organization.findUnique({where:{slug},include:{services:{where:{active:true}},barbers:{where:{active:true},select:{id:true,displayName:true}}}});

app.get('/api/health',asyncRoute(async(_q,res)=>{await db.$queryRaw`SELECT 1`;res.json({status:'ok'});}));
app.get('/api/public/:slug',asyncRoute(async(req,res)=>{const org=await publicOrg(String(req.params.slug));if(!org)return fail(res,404,'ORGANIZATION_NOT_FOUND','Barbería no encontrada.');if(org.status!==OrganizationStatus.ACTIVE||org.subscriptionExpiresAt<=new Date())return fail(res,403,'ORGANIZATION_SUSPENDED','Esta barbería no está disponible temporalmente.');res.json({success:true,data:org});}));
app.get('/api/public/:slug/availability',asyncRoute(async(req,res)=>{const schema=z.object({date:z.coerce.date(),serviceId:z.string().uuid().optional(),barberId:z.string().uuid().optional()});const q=schema.parse(req.query);const org=await db.organization.findUnique({where:{slug:String(req.params.slug)}});if(!org||org.status!==OrganizationStatus.ACTIVE||org.subscriptionExpiresAt<=new Date())return fail(res,404,'ORGANIZATION_UNAVAILABLE','Esta barbería no está disponible temporalmente.');const now=new Date(), limit=new Date(now);limit.setDate(limit.getDate()+7);if(q.date<new Date(now.toDateString())||q.date>limit)return fail(res,422,'DATE_OUT_OF_RANGE','Solo puedes reservar entre hoy y los próximos 7 días.');const service=q.serviceId?await db.service.findFirst({where:{id:q.serviceId,organizationId:org.id,active:true}}):null;if(q.serviceId&&!service)return fail(res,404,'SERVICE_NOT_FOUND','Servicio no encontrado.');const duration=service?.durationMinutes||30;const candidates=await db.barber.findMany({where:{organizationId:org.id,active:true,...(q.barberId?{id:q.barberId}:{})}});const day=q.date.getDay();const result=[] as {barberId:string;time:string}[];for(const b of candidates){const schedule=await db.daySchedule.findFirst({where:{organizationId:org.id,weekday:day,OR:[{barberId:b.id},{barberId:null}]},orderBy:{barberId:'desc'}});if(!schedule||schedule.closed)continue;const start=timeOnDate(q.date,schedule.openTime),end=timeOnDate(q.date,schedule.closeTime);const [appointments,blocks]=await Promise.all([db.appointment.findMany({where:{barberId:b.id,status:AppointmentStatus.CONFIRMED,startsAt:{gte:new Date(q.date.toDateString()),lt:new Date(new Date(q.date).setDate(q.date.getDate()+1))}}}),db.blockedSlot.findMany({where:{organizationId:org.id,startsAt:{lt:end},endsAt:{gt:start},OR:[{barberId:b.id},{barberId:null}]}})]);for(let slot=new Date(start);slot.getTime()+duration*60000<=end.getTime();slot=new Date(slot.getTime()+30*60000)){const slotEnd=new Date(slot.getTime()+duration*60000);const inBreak=schedule.breakStart&&slot<timeOnDate(q.date,schedule.breakEnd!)&&slotEnd>timeOnDate(q.date,schedule.breakStart);const conflict=[...appointments,...blocks].some(x=>slot<x.endsAt&&slotEnd>x.startsAt);if(!inBreak&&!conflict&&slot>=now)result.push({barberId:b.id,time:slot.toISOString()})}}res.json({success:true,data:result});}));

app.post('/api/auth/login',asyncRoute(async(req,res)=>{const v=z.object({email:z.string().email(),password:z.string().min(8)}).parse(req.body);const user=await db.user.findUnique({where:{email:v.email},include:{organization:true}});if(!user||!user.active||!await bcrypt.compare(v.password,user.passwordHash))return fail(res,401,'INVALID_CREDENTIALS','Credenciales inválidas.');if(user.role!==Role.SUPERADMIN&&(!user.organization||user.organization.status!==OrganizationStatus.ACTIVE||user.organization.subscriptionExpiresAt<=new Date()))return fail(res,403,'ORGANIZATION_SUSPENDED','Esta barbería no está disponible temporalmente.');const token=tokenFor(user);res.cookie('access_token',token,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:8*3600_000}).json({success:true,data:{token,user:{id:user.id,name:user.name,role:user.role,organizationId:user.organizationId}}});}));
app.post('/api/auth/logout',(_q,res)=>res.clearCookie('access_token').json({success:true}));
app.post('/api/auth/otp/request',rateLimit({windowMs:15*60_000,max:5}),asyncRoute(async(req,res)=>{const v=z.object({slug:z.string(),phone:z.string().min(8).max(20)}).parse(req.body);const org=await db.organization.findUnique({where:{slug:v.slug}});if(!org)return fail(res,404,'ORGANIZATION_NOT_FOUND','Barbería no encontrada.');const code=crypto.randomInt(100000,1000000).toString();await db.otp.create({data:{organizationId:org.id,phone:v.phone,codeHash:await bcrypt.hash(code,10),expiresAt:new Date(Date.now()+300000)}});await sendN8n('otp.requested',{phone:v.phone,code,expires_in:300,organization_id:org.id});res.json({success:true,data:{expiresIn:300}});}));
app.post('/api/auth/register',asyncRoute(async(req,res)=>{const v=z.object({slug:z.string(),name:z.string().min(2),phone:z.string().min(8),password:z.string().min(8),code:z.string().length(6)}).parse(req.body);const org=await db.organization.findUnique({where:{slug:v.slug}});if(!org)return fail(res,404,'ORGANIZATION_NOT_FOUND','Barbería no encontrada.');const otp=await db.otp.findFirst({where:{organizationId:org.id,phone:v.phone,usedAt:null,expiresAt:{gt:new Date()},attempts:{lt:5}},orderBy:{createdAt:'desc'}});if(!otp||!await bcrypt.compare(v.code,otp.codeHash)){if(otp)await db.otp.update({where:{id:otp.id},data:{attempts:{increment:1}}});return fail(res,422,'INVALID_OTP','Código inválido o expirado.');}try{const user=await db.$transaction(async tx=>{await tx.otp.update({where:{id:otp.id},data:{usedAt:new Date()}});return tx.user.create({data:{name:v.name,phone:v.phone,passwordHash:await bcrypt.hash(v.password,12),role:Role.CLIENT,organizationId:org.id,client:{create:{organizationId:org.id,name:v.name,phone:v.phone,verifiedAt:new Date()}}}})});res.status(201).json({success:true,data:{token:tokenFor(user)}})}catch{return fail(res,409,'PHONE_ALREADY_EXISTS','Ya existe un cliente con este teléfono.')}}));

app.post('/api/appointments',auth,activeTenant,role(Role.CLIENT),asyncRoute(async(req,res)=>{const v=z.object({serviceId:z.string().uuid(),barberId:z.string().uuid().optional(),startsAt:z.coerce.date()}).parse(req.body);const orgId=req.auth!.organizationId!, now=new Date(),max=new Date(now);max.setDate(max.getDate()+7);if(v.startsAt<now||v.startsAt>max)return fail(res,422,'DATE_OUT_OF_RANGE','Solo puedes reservar entre hoy y los próximos 7 días.');const client=await db.client.findUnique({where:{userId:req.auth!.id}});if(!client)return fail(res,403,'CLIENT_REQUIRED','Perfil de cliente requerido.');try{const appointment=await db.$transaction(async tx=>{const [service,activeCount]=await Promise.all([tx.service.findFirst({where:{id:v.serviceId,organizationId:orgId,active:true}}),tx.appointment.count({where:{clientId:client.id,status:AppointmentStatus.CONFIRMED,startsAt:{gte:new Date(now.toDateString()),lte:max}}})]);if(!service)throw new Error('SERVICE_NOT_FOUND');if(activeCount>=2)throw new Error('APPOINTMENT_LIMIT');let barberId=v.barberId;if(!barberId){const a=await tx.barber.findFirst({where:{organizationId:orgId,active:true,appointments:{none:{status:AppointmentStatus.CONFIRMED,startsAt:{lt:new Date(v.startsAt.getTime()+service.durationMinutes*60000)},endsAt:{gt:v.startsAt}}}},orderBy:{displayName:'asc'}});barberId=a?.id}const barber=barberId&&await tx.barber.findFirst({where:{id:barberId,organizationId:orgId,active:true}});if(!barber)throw new Error('APPOINTMENT_UNAVAILABLE');const endsAt=new Date(v.startsAt.getTime()+service.durationMinutes*60000);const conflicts=await tx.appointment.count({where:{barberId:barber.id,status:AppointmentStatus.CONFIRMED,startsAt:{lt:endsAt},endsAt:{gt:v.startsAt}}});if(conflicts)throw new Error('APPOINTMENT_UNAVAILABLE');return tx.appointment.create({data:{organizationId:orgId,barberId:barber.id,clientId:client.id,serviceId:service.id,clientName:client.name,clientPhone:client.phone,startsAt:v.startsAt,endsAt,price:service.price}})}, {isolationLevel:'Serializable'});await sendN8n('booking.created',{appointment_id:appointment.id,organization_id:orgId,appointment});res.status(201).json({success:true,data:appointment});}catch(e){const x=e as Error;const code=x.message==='APPOINTMENT_LIMIT'?'APPOINTMENT_LIMIT':x.message==='SERVICE_NOT_FOUND'?'SERVICE_NOT_FOUND':'APPOINTMENT_UNAVAILABLE';return fail(res,code==='APPOINTMENT_LIMIT'?422:409,code,code==='APPOINTMENT_LIMIT'?'Has alcanzado el máximo de 2 citas activas.':'El horario seleccionado ya no está disponible.')}}));
app.get('/api/appointments',auth,activeTenant,asyncRoute(async(req,res)=>{const where:any={organizationId:req.auth!.organizationId};if(req.auth!.role===Role.CLIENT){const c=await db.client.findUnique({where:{userId:req.auth!.id}});where.clientId=c?.id}else if(req.auth!.role===Role.BARBER){const b=await db.barber.findUnique({where:{userId:req.auth!.id}});where.barberId=b?.id}res.json({success:true,data:await db.appointment.findMany({where,include:{service:true,barber:true},orderBy:{startsAt:'asc'}})});}));
app.patch('/api/appointments/:id/cancel',auth,activeTenant,asyncRoute(async(req,res)=>{const a=await db.appointment.findFirst({where:{id:String(req.params.id),organizationId:req.auth!.organizationId!}});if(!a)return fail(res,404,'APPOINTMENT_NOT_FOUND','Cita no encontrada.');if(req.auth!.role===Role.CLIENT){const c=await db.client.findUnique({where:{userId:req.auth!.id}});if(a.clientId!==c?.id)return fail(res,403,'FORBIDDEN','No puedes cancelar esta cita.')}res.json({success:true,data:await db.appointment.update({where:{id:a.id},data:{status:AppointmentStatus.CANCELLED}})});}));

app.get('/api/services',auth,activeTenant,role(Role.OWNER,Role.BARBER),asyncRoute(async(req,res)=>res.json({success:true,data:await db.service.findMany({where:{organizationId:req.auth!.organizationId!}})})));
app.post('/api/services',auth,activeTenant,role(Role.OWNER),asyncRoute(async(req,res)=>{const v=z.object({name:z.string().min(2),description:z.string().optional(),price:z.number().int().positive(),durationMinutes:z.number().int().min(15).max(360)}).parse(req.body);res.status(201).json({success:true,data:await db.service.create({data:{...v,organizationId:req.auth!.organizationId!}})});}));
app.get('/api/barbers',auth,activeTenant,role(Role.OWNER,Role.BARBER),asyncRoute(async(req,res)=>res.json({success:true,data:await db.barber.findMany({where:{organizationId:req.auth!.organizationId!}})})));
app.post('/api/barbers',auth,activeTenant,role(Role.OWNER),asyncRoute(async(req,res)=>{const v=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(8)}).parse(req.body);const orgId=req.auth!.organizationId!;const org=await db.organization.findUniqueOrThrow({where:{id:orgId}});if(await db.barber.count({where:{organizationId:orgId,active:true}})>=org.maxBarbers)return fail(res,422,'BARBER_LIMIT','Se alcanzó el límite de barberos.');const u=await db.user.create({data:{name:v.name,email:v.email,passwordHash:await bcrypt.hash(v.password,12),role:Role.BARBER,organizationId:orgId,barber:{create:{organizationId:orgId,displayName:v.name}}}});res.status(201).json({success:true,data:u});}));
app.post('/api/blocks',auth,activeTenant,role(Role.OWNER,Role.BARBER),asyncRoute(async(req,res)=>{const v=z.object({barberId:z.string().uuid().optional(),startsAt:z.coerce.date(),endsAt:z.coerce.date(),reason:z.string().max(200).optional()}).refine(x=>x.endsAt>x.startsAt).parse(req.body);let barberId=v.barberId;if(req.auth!.role===Role.BARBER)barberId=(await db.barber.findUnique({where:{userId:req.auth!.id}}))?.id;if(!barberId)return fail(res,422,'BARBER_REQUIRED','Selecciona un barbero.');res.status(201).json({success:true,data:await db.blockedSlot.create({data:{...v,barberId,organizationId:req.auth!.organizationId!}})});}));
app.get('/api/vip',auth,activeTenant,role(Role.OWNER,Role.BARBER),asyncRoute(async(req,res)=>{const where:any={organizationId:req.auth!.organizationId};if(req.auth!.role===Role.BARBER)where.barberId=(await db.barber.findUnique({where:{userId:req.auth!.id}}))?.id;res.json({success:true,data:await db.vipSchedule.findMany({where,include:{client:true,barber:true,exceptions:true}})});}));
app.post('/api/vip',auth,activeTenant,role(Role.OWNER,Role.BARBER),asyncRoute(async(req,res)=>{const v=z.object({clientId:z.string().uuid(),barberId:z.string().uuid(),weekday:z.number().int().min(0).max(6),time:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),frequency:z.nativeEnum(VipFrequency),serviceId:z.string().uuid().optional()}).parse(req.body);if(req.auth!.role===Role.BARBER){const b=await db.barber.findUnique({where:{userId:req.auth!.id}});if(v.barberId!==b?.id)return fail(res,403,'FORBIDDEN','Solo puedes gestionar tus VIP.')}res.status(201).json({success:true,data:await db.vipSchedule.create({data:{...v,organizationId:req.auth!.organizationId!}})});}));
app.post('/api/vip/:id/exceptions',auth,activeTenant,role(Role.OWNER,Role.BARBER),asyncRoute(async(req,res)=>{const v=z.object({date:z.coerce.date(),type:z.nativeEnum(VipExceptionType),rescheduledAt:z.coerce.date().optional()}).refine(x=>x.type!==VipExceptionType.RESCHEDULE||!!x.rescheduledAt).parse(req.body);const vip=await db.vipSchedule.findFirst({where:{id:String(req.params.id),organizationId:req.auth!.organizationId!}});if(!vip)return fail(res,404,'VIP_NOT_FOUND','VIP no encontrado.');res.json({success:true,data:await db.vipException.upsert({where:{vipScheduleId_date:{vipScheduleId:vip.id,date:v.date}},update:v,create:{...v,vipScheduleId:vip.id}})});}));

app.get('/api/superadmin/stats',auth,role(Role.SUPERADMIN),asyncRoute(async(_q,res)=>{const [total,active,suspended,totalBarbers,totalAppointments]=await Promise.all([db.organization.count(),db.organization.count({where:{status:OrganizationStatus.ACTIVE}}),db.organization.count({where:{status:OrganizationStatus.SUSPENDED}}),db.barber.count(),db.appointment.count()]);res.json({success:true,data:{totalOrganizations:total,active,suspended,expiringSoon:await db.organization.count({where:{subscriptionExpiresAt:{lte:new Date(Date.now()+7*864e5),gt:new Date()}}}),totalBarbers,totalAppointments}});}));
app.get('/api/superadmin/organizations',auth,role(Role.SUPERADMIN),asyncRoute(async(_q,res)=>res.json({success:true,data:await db.organization.findMany({include:{_count:{select:{barbers:true,appointments:true}}},orderBy:{createdAt:'desc'}})})));
app.post('/api/superadmin/organizations',auth,role(Role.SUPERADMIN),asyncRoute(async(req,res)=>{const v=z.object({name:z.string().min(2),slug:z.string().regex(/^[a-z0-9-]+$/),subscriptionExpiresAt:z.coerce.date(),maxBarbers:z.number().int().min(1).max(100)}).parse(req.body);res.status(201).json({success:true,data:await db.organization.create({data:v})});}));
app.patch('/api/superadmin/organizations/:id',auth,role(Role.SUPERADMIN),asyncRoute(async(req,res)=>{const v=z.object({status:z.nativeEnum(OrganizationStatus).optional(),subscriptionExpiresAt:z.coerce.date().optional(),maxBarbers:z.number().int().min(1).max(100).optional(),name:z.string().min(2).optional()}).parse(req.body);res.json({success:true,data:await db.organization.update({where:{id:String(req.params.id)},data:v})});}));
app.post('/api/webhooks/otp-request',webhookAuth,(req,res)=>res.json({success:true,event:'otp-request.accepted'})); app.post('/api/webhooks/booking-created',webhookAuth,(req,res)=>res.json({success:true,event:'booking-created.accepted'}));
app.get('/api/cron/reminders-24h',cronAuth,asyncRoute(async(_q,res)=>{const start=new Date(Date.now()+23*3600e3),end=new Date(Date.now()+25*3600e3);const appointments=await db.appointment.findMany({where:{status:AppointmentStatus.CONFIRMED,startsAt:{gte:start,lt:end},reminderSentAt:null},include:{client:true,barber:true,service:true}});for(const a of appointments){await sendN8n('booking.reminder',{appointment_id:a.id,client:a.client,barber:a.barber,service:a.service,appointment:a});await db.appointment.update({where:{id:a.id},data:{reminderSentAt:new Date()}})}res.json({success:true,data:{processed:appointments.length}});}));
app.get('/api/cron/subscription-checks',cronAuth,asyncRoute(async(_q,res)=>{const now=new Date();const expired=await db.organization.updateMany({where:{status:OrganizationStatus.ACTIVE,subscriptionExpiresAt:{lt:now}},data:{status:OrganizationStatus.SUSPENDED}});const expiring=await db.organization.count({where:{status:OrganizationStatus.ACTIVE,subscriptionExpiresAt:{gte:now,lte:new Date(now.getTime()+7*864e5)}}});res.json({success:true,data:{suspended:expired.count,expiringSoon:expiring}});}));
app.use((err:any,_q:Request,res:Response,_n:NextFunction)=>{if(err instanceof z.ZodError)return fail(res,422,'VALIDATION_ERROR',err.issues.map(x=>x.message).join(', '));console.error(err);return fail(res,500,'INTERNAL_ERROR','Ocurrió un error inesperado.');}); app.listen(PORT,()=>console.log(`ASYS API on :${PORT}`));
